repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=500"]
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-shebang-scripts-are-executable
    - id: pretty-format-json
      args: ["--autofix"]
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-vcs-permalinks
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: file-contents-sorter
    - id: fix-byte-order-marker
    - id: fix-encoding-pragma
    - id: forbid-new-submodules
    - id: mixed-line-ending
      args: ["--fix=lf"]
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
    - id: trailing-whitespace
- repo: https://github.com/kumaraditya303/mirrors-pyright
  rev: "v1.1.248"
  hooks:
  - id: pyright
- repo: https://github.com/PyCQA/isort
  rev: "5.10.1"
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/pylint
  rev: "v2.14.0-b1"
  hooks:
  - id: pylint
    additional_dependencies:
    - toml==0.10.2
- repo: https://github.com/PyCQA/bandit
  rev: "1.7.4"
  hooks:
  - id: bandit
    args: ["-c", "pyproject.toml", "--"]
    additional_dependencies:
    - toml==0.10.2
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    args: [
      --ignore-words=.codespellignore
    ]
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.4.0
  hooks:
  - id: markdownlint-cli2
- repo: https://github.com/Holzhaus/sourceheaders
  rev: v0.0.4
  hooks:
  - id: sourceheaders
- repo: https://github.com/jorisroovers/gitlint
  rev: "v0.17.0"
  hooks:
  - id: gitlint
