name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install package
      run: pip install .

    - name: Run tests
      run: python -m unittest discover -v

    - name: Display help text
      run: sourceheaders --help
